import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'

const about = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basanda Lu IT Solutions | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1 className={styles.heading}>Our Story</h1>
      <div className={styles.aboutContainer}>
        <div className={styles.aboutLeft}>
          <p className={styles.description}>Basanda LU IT Solutions started out as an IT services company in 2020. We offer services such as Web Design, Custom Software development, Graphic Design, IT Support and Consultancy and SEO. We are currently operating from Mbombela but we can provide services across the rest of South Africa. Our target clients are small to medium sized companies seeking to improve their brand awareness or stremline their operations using cutting edge IT solutions. </p>
          <h3 className={styles.heading3}>Our Mission</h3>
          <p className={styles.description}>To add value to our clients businesses through technological innovation.</p>
          <h3 className={styles.heading3}>Our Vision</h3>
          <p className={styles.description}>Build a world class organisation that is respected by all. We intend to create value for our stakeholders ie our clients, employees and vendors.</p>
        </div>
        <div className={styles.aboutRight}>
            <div  className={styles.aboutImage1}>
                    <Image
                        src="/aboutImg.jpg"
                        alt="about aboutImg"
                        width="600"
                        height="600"
                        objectFit= "cover"
                        className={styles.img}
                    />
              </div>
        </div> 
      </div>
      <h1 className={styles.heading}>Our Team</h1>
    </div>
  )
}

export default about