import React from 'react'
import Head from 'next/head'
import styles from '../styles/Blogs.module.css'

const blogs = () => {
  return (
    <div>
      <Head>
        <title>Basanda Lu IT Solutions | Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.header}>Blogs</h1>
      </div>
    </div>
  )
}

export default blogs