import React from 'react'
import Head from 'next/head'
import Contact from '../components/Contact'
import styles from '../styles/ContactUs.module.css'

const contactUs = () => {
  return (
    <>
    <Head>
        <title>Basanda Lu IT Solutions | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.contactHero}></div>
      <div className={styles.container}>
          <Contact />
      </div>
    </>
  )
}

export default contactUs