import Head from 'next/head'
import Image from 'next/image'
import AboutSection from '../components/AboutSection'
import Contact from '../components/Contact'
import CTASection from '../components/CTASection'
import Hero from '../components/Hero'
import OurServices from '../components/OurServices'
import Portfolio from '../components/Portfolio'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basanda Lu IT Solutions | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero />
      <AboutSection />
      <OurServices />
      <CTASection />
      <Portfolio />
      <Contact />
      
    </div>
  )
}
