import React from 'react'
import Head from 'next/head'
import Portfolio from '../components/Portfolio'
import styles from '../styles/PortfolioPage.module.css'


const projects = () => {
  return (
    <div>
      <Head>
        <title>Basanda Lu IT Solutions | Our Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.portfolioPageHero}>
        <Portfolio />
      </div>
    </div>
  )
}

export default projects