import React from 'react'
import Head from 'next/head'
import OurServices from '../components/OurServices'
import styles from '../styles/OurServices.module.css'

const services = () => {
  return (
    <div>
      <Head>
        <title>Basanda Lu IT Solutions | Our Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.servicePageHero}></div>
        <OurServices />
    </div>
  )
}

export default services